_wandb:
    value:
        cli_version: 0.24.0
        e:
            1hhmcve1nf3w0547yakzpwt22xxdbll5:
                args:
                    - --train_npy_dir
                    - /mnt/nas_syy/default/huada_signal_llm/dataset/dna/human_min0_max2_read96655/memap/train
                    - --evaluation_npy_dir
                    - /mnt/nas_syy/default/huada_signal_llm/dataset/dna/human_min0_max2_read96655/memap/validation
                    - --output_model_path
                    - models/porepgt_vqe_tokenizer
                    - --batch_size
                    - "8"
                    - --lr
                    - "0.00005"
                    - --num_epochs
                    - "50"
                    - --codebook_size
                    - "65536"
                    - --chunk_size
                    - "12000"
                    - --num_workers
                    - "16"
                    - --val_ratio
                    - "0.01"
                    - --save_checkpoint_every_spoch
                    - "1000"
                    - --loss_log_interval
                    - "10"
                    - --commitment_weight
                    - "0.250"
                    - --codebook_diversity_loss_weight
                    - "0.00000"
                    - --orthogonal_reg_weight
                    - "0.000"
                    - --checkpoint_path
                    - models_old/nanopore_signal_tokenizer.pth.spoch26000.pth
                    - --cnn_type
                    - "1"
                    - --init_codebook_path
                    - /mnt/nas_syy/default/poregpt/shared/kmc_models_apple_c64k_redo1/memap_train_clustered_10p_centroids_k65536.npy
                    - --cnn_checkpoint_path
                    - /mnt/nas_syy/default/poregpt/shared/cnn_models_apple_type1/checkpoints/nanopore_signal_tokenizer.pth.epoch28.pth
                    - --freeze_cnn
                    - "0"
                    - --global_batch_size
                    - "256"
                    - --device_micro_batch_size
                    - "4"
                    - --do_evaluate
                cpu_count: 21
                cpu_count_logical: 42
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "528046399488"
                        used: "165714427904"
                email: jiaoshuaihit@gmail.com
                executable: /data/miniconda/envs/bonito_py310/bin/python
                git:
                    commit: 86663c16e2d4a934d995b78f930b7153224675e5
                    remote: git@github-lovearthai:lovearthai/poregpt.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-6a131213-6dad-9df2-bbc4-c322bd288044
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-5f6965ce-4a2b-80d6-1200-cb5b314f33ec
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-a6beda60-a0b4-5ea7-bfaa-48e533d37019
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-fe73e7e9-218e-08f4-5e92-b93b6db06181
                host: zhongziban-4-1
                memory:
                    total: "506484330496"
                os: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
                program: -m poregpt.tokenizers.vqe_tokenizer.vqe_train
                python: CPython 3.10.19
                root: /mnt/nas_syy/default/poregpt/poregpt/poregpt/workflows/nanopore_llm_workflow/scripts/vqe_workflow/tmp
                startedAt: "2026-01-20T05:36:56.807249Z"
                writerId: 1hhmcve1nf3w0547yakzpwt22xxdbll5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 8
chunk_size:
    value: 12000
codebook_diversity_loss_weight:
    value: 0
codebook_size:
    value: 65536
commitment_weight:
    value: 0.25
lr:
    value: 5e-05
num_epochs:
    value: 50
orthogonal_reg_weight:
    value: 0
update_loss_weight_every:
    value: 10
world_size:
    value: 4
